apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-gateway-configmap
  namespace: {{NAMESPACE}}
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /etc/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
        log_format  main
        '[GATEWAY] - '
        '$remote_addr - - '
        '[$time_local] '
        '"$request_method '
        '$request_uri" '
        '$status -'
        ' http:/$request_uri.default.svc.cluster.local';

        access_log  /etc/nginx/access.log main;
        #access_log  /var/log/nginx/access.log main;
        access_log on;

        server {
                listen       80;
                server_name  _;
                location / {
                    resolver kube-dns.kube-system.svc.cluster.local;
                    proxy_pass http:/$request_uri.default.svc.cluster.local/api/v1;
                    proxy_http_version 1.1;
                }
        }
    }
